### ISSUE TITLE
My computer doesn't trust the file.

### ISSUE THREAD

**Issue by SkipcaU** [R2NorthstarTools/VTOL#101]
I keep trying to go into my files to allow permission to VTOL, but it won't let me. I'm not the best when it comes to doing things on computers, but I just want to play online Titanfall again. Does anyone know how to make my computer trust the file? If so thanks.

**Comment by BigSpice** [comment]
All good, its that i dont have microsoft certs (cost alot)
So UAC flags it as a third party app.
Its normal for any non windows certified exe.

**Comment by SkipcaU** [comment]
So I just have to download that app and then I can download the launcher?

**Comment by SkipcaU** [comment]
I got it to install thank you so much.

**Comment by BigSpice** [comment]
Understood, Closing as complete.
