### ISSUE TITLE
Black Window

### ISSUE THREAD

**Issue by SignalRaptor** [R2NorthstarTools/VTOL#58]
Both the portable and installed version just open black screens for about 10 seconds, then close. I have the dotnet 6.0.16 desktop runtime libraries for x86 and x64 installed.
![image](https://user-images.githubusercontent.com/23458348/232260118-493c68cb-c6ca-4618-9011-8423b59f2b3f.png)

**Comment by SignalRaptor** [comment]
I ran the installer, granted it admin during install, installed to C:\Program Files (x86)\VTOL\
Titanfall is located on G:\Steam\Steamapps\common\titanfall2 if that matters
OS: Windows 10 22H2

**Comment by BigSpice** [comment]
On it and investigating currently.

**Comment by BigSpice** [comment]
found cause. updating file checks

**Comment by reynonic** [comment]
Glad it isn't just me. I tried this on 2 Win 11 PCs. One didn't have an issue, but the other did. Tried making a VM on the Dell I use as a server that had the issue and the same issue occurred. Was trying to track down via ProcMon and various other tools. Thanks for your work @BigSpice Do you by chance have an idea when this will be fixed?

**Comment by BigSpice** [comment]
Hopefully tonight, already found the little bastard. It was my logging and file service.

**Comment by BigSpice** [comment]
please update to version v2.2.9 and see if this resolves the issue @SignalRaptor

**Comment by reynonic** [comment]
That fixed mine. Thanks!

**Comment by SignalRaptor** [comment]
![image](https://user-images.githubusercontent.com/23458348/233079511-2d224da0-e983-4ba5-96ed-5712ffbe1794.png)
Looks like it's running! Thanks a bunch!
