### ISSUE TITLE
Unused strings?

### ISSUE THREAD

**Issue by WofWca** [R2NorthstarTools/VTOL#69]
https://github.com/R2NorthstarTools/VTOL/blob/356eb5d159b4130ebbd6b5e19d6fc4dd40ce05cc/VTOL_2.0.0/Resources/Languages/Language.resx#L741-L746

Strings with such keys do not appear to be used in the source code:

https://github.com/search?q=repo%3AR2NorthstarTools%2FVTOL+PARENTTO&type=code

But they still appear on Weblate. Do they still need to be translated?

**Comment by BigSpice** [comment]
Yes please, they are underlying work for a new framework.
