### ISSUE TITLE
Pop up repeatedly appears asking to delete "Mod Settings" mod for being allegedly outdated

### ISSUE THREAD

**Issue by mikeadox** [R2NorthstarTools/VTOL#70]
**Description**
When installing the latest version of the "Mod Settings" mod, a Pop up will appear every time I open my mod library, 
asking to uninstall "Mod Settings" due to it being "Deprecated" (outdated?).

1. Install the latest version of "Mod Settings" either manually or from the built in 
   Thunderstone browser that is included in the VTOL Client.
3. Open the "Mods" tab to see your installed mods.
4. Pop up appears asking to delete Mod Settings.

**Expected behavior**
That Pop up shouldn't appear if the latest Version of the mod is already installed.

**Screenshots**
![image](https://github.com/R2NorthstarTools/VTOL/assets/133385292/e6f994cf-ba9a-4831-8610-e0c1f869b95c)

**My PC**
 - OS: Windows 11 Pro
 - Version 22H2

**Comment by F1F7Y** [comment]
Any and all versions of modsettings are outdated as its shipped with northstar.

Northstar itself automatically disables modsettings to prevent conflicts so having it installed doesnt do anything.

**Comment by BigSpice** [comment]
will be removed, thank you :)

**Comment by BigSpice** [comment]
removed and on new release

**Comment by BigSpice** [comment]
on 3.0.3
