### ISSUE TITLE
Delete previous core mods on update

### ISSUE THREAD

**Issue by GeckoEidechse** [R2NorthstarTools/VTOL#81]
### Introduction

To my knowledge VTOL currently simply overwrites existing files on Northstar updates. While this has been fine so far in terms of update stability, it is somewhat limiting for upstream Northstar.

In particular, given our past recommendations of simply overwriting files when updating we could never ship an update that removes a script source file for one of the core Northstar mods (`Northstar.{Client,Custom,CustomServers}`) again.
This made development somewhat cumbersome as adding any script file had to be carefully considered due to not being able to remove said file again once shipped.

As such [our recommendations for (manually) updating Northstar](https://r2northstar.gitbook.io/r2northstar-wiki/installing-northstar/manual-installation#updating-northstar) have since changed to first clearing existing `Northstar.*` mods folders and only then adding the new script files from the release.
(Similarly [FlightCore was also updated accordingly](https://github.com/R2NorthstarTools/FlightCore/pull/659).)

This finally allows upstream Northstar to push out an update that also removes script files from core mods again.

### How VTOL falls into this

Given that a large chunk of Northstar players use VTOL to maintain their installation, I'm hoping VTOL can follow suite on this, so that we can ensure that no players encounter any issues on future updates that might remove script source files again.

Note that we don't have an exact time frame on when such an update might release, however it's probably best to already have the change in VTOL implemented and shipped in order to avoid any stress once such an update should hit ^^

### TL;DR

Before extracting a new update into Titanfall2 folder, delete any existing `Northstar.Custom`, `Northstar.Client`, and `Northstar.CustomServers` folders in the mods directory.
For future proofing (e.g. when `Northstar.Coop` surely releases one day), it's probably to even just delete all `Northstar.*` folders in the `mods` directory before applying an update.

**Comment by BigSpice** [comment]
on it

**Comment by BigSpice** [comment]
finished

**Comment by BigSpice** [comment]
> finished

![image](https://github.com/R2NorthstarTools/VTOL/assets/23240514/380bea3e-67ff-4da4-b1ee-3de71c36a1f3)
