### ISSUE TITLE
VTOL crashing when trying to view installed mods

### ISSUE THREAD

**Issue by NERD-NATO** [R2NorthstarTools/VTOL#89]
**Describe the bug**
Downloaded VTOL, went looking for some mods on the browser. Downloaded some, and when trying to view my mods page on the launcher, it crashes.

**To Reproduce**
1: open VTOL
2: download mods from browser (currently using HUDrevamp and FactionLock)
3: click on mods tab
4: crash

**Expected behavior**
Mods page opening normally with my mods there.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Win10
 - Version 22H2

**Additional context**
The mods page opened normally when no mods were installed, this only happened after downloading.

**Comment by BigSpice** [comment]
sincerest apologies,

the fix is ready, ive just been battling a lower back injury as of recently.
uploading today :)
Please bump if no commit is seen 6 your local time.
@NERD-NATO

**Comment by AksharDP** [comment]
> @NERD-NATO also please try the nightly if it works, it will tell us if its ready to ship rn. https://nightly.link/R2NorthstarTools/VTOL/workflows/dotnet-desktop/master/VTOL_NIGHTLY-artifact

Also having the same issue, nightly link doesn't work.

**Comment by BigSpice** [comment]
Please kindly forward the log created under 
`C:\Users\<USERNAME>\AppData\Roaming\VTOL_DATA\Logs`

I am currently in need of more information.
@AksharDP 
@NERD-NATO

**Comment by BigSpice** [comment]
Please try either the portable or new 3.0.5 release. 
@AksharDP
@NERD-NATO

**Comment by NERD-NATO** [comment]
Hey, sorry for the delay. It's working perfectly, thanks.
