### ISSUE TITLE
What happened to setting the installation location?

### ISSUE THREAD

**Issue by HatWearingMann** [R2NorthstarTools/VTOL#92]
**Is your feature request related to a problem? Please describe.**
I cannot set the installation location during setup anymore.

**Describe the solution you'd like**
Add an option of setting the installation location to the installer.

**Describe alternatives you've considered**
Downloading the portable version.

**Additional context**
I am 90% sure, that an older version of this software had such an option.

**Comment by BigSpice** [comment]
Currently Portable is setup as a oneclick Exe,
To install you can go to the current release page and use the 5.0.5 MSI installer.

https://github.com/R2NorthstarTools/VTOL/releases/tag/v3.0.5

(It was a bit of a complaint that portable wasnt working as intended earlier last year.)

**Comment by HatWearingMann** [comment]
That doesn't really answer my question, but yeah. The portable version is good enough.
