### ISSUE TITLE
Mods don't show up in the mods section

### ISSUE THREAD

**Issue by Sirinchocolate** [R2NorthstarTools/VTOL#93]
**Describe the bug**
Mods don't show up in the mods section

**To Reproduce**
1. Have an older version, and update. (might be optional)
2. Check your mods tab, not even NS will be in there.

**Expected behavior**
I expect to be able to see and disable my mods.

**Screenshots**
![Screenshot 2024-04-28 114317](https://github.com/R2NorthstarTools/VTOL/assets/91801470/1020a4e2-00b6-4046-8a35-f96cb21bc80c)
![Screenshot 2024-04-28 114256](https://github.com/R2NorthstarTools/VTOL/assets/91801470/382e0c34-18bf-4f2f-9a72-6361bf1c96e4)

**Desktop (please complete the following information):**
 - OS: [W11 home]
 - Version [23H2, 22631.3447]

**Additional context**

**Comment by BigSpice** [comment]
Hey there @Sirinchocolate,

Apoligies on the error,
would it be alright to obtain the log created under
`C:\Users\<USERNAME>\AppData\Roaming\VTOL_DATA\Logs`

I am currently in need of more information on your specific issue.

**Comment by Sirinchocolate** [comment]
There exists no logs folder in VTOL_DATA.

![Screenshot 2024-04-28 184056](https://github.com/R2NorthstarTools/VTOL/assets/91801470/381b84a8-cdfb-4044-b398-d92094499663)

**Comment by BigSpice** [comment]
found the issue,

Pushing a fix before Wednesday:D 
@Sirinchocolate

**Comment by gustis40g** [comment]
Hi @BigSpice, 

I'm experiencing the exact same issue, attached is my log file.
[User - Log2024071123.log](https://github.com/user-attachments/files/16183692/User.-.Log2024071123.log)

I have no clue why it even mentions the D: drive here since neither VTOL nor Titanfall is installed in the D: drive, in fact my D: drive is just an long term storage unit and the last edited file in it was touched last year

**Comment by BigSpice** [comment]
On this, apoloiges, alot happening irl rn.

**Comment by BigSpice** [comment]
Fixed as of September 10th

**Comment by ReKylee** [comment]
Hi, I don't think this is fixed. 
Everytime you install a mod, it corrupts the `enabledmods.json` file.


![Image](https://github.com/user-attachments/assets/480d12c7-32f6-482b-b288-ad6cc78bf2c2)


After you re-launch Northstar then it fixes itself but before that this is what happens.
I think this is related to this issue, considering they happened one after another for me.

**Comment by BigSpice** [comment]
Please send me.the log folder under documents VTOL ❤️

**Comment by ReKylee** [comment]
[logs.zip](https://github.com/user-attachments/files/19712590/logs.zip)

**Comment by BigSpice** [comment]
thank you ❤
